PKG_NAME	= mathweb-omdoc
PKG_MOGUL_URI	= mogul:/mathweb/omdoc
PKG_URI		= x-ozlib://mathweb/omdoc
PKG_URI_AUX	= $(PKG_URI)/sem

PKG_SOURCES	= $(wildcard *.sem.oz)
PKG_INSTALLS	= 
PKG_INSTALLS_AUX= \
	metadata.sem.ozf \
	omdoc.sem.ozf \
        omdobj.sem.ozf \
	omobj.sem.ozf
PKG_INSTALLS_DOC=
PKG_INSTALLS_INC=
PKG_INSTALLS_BIN=
PKG_SUBDIRS	=
PKG_API		= $(wildcard *.oz) 
PKG_UPDATE	= tgz

PKG_METHOD	= find
