PREFIX          = ../..
COLLFILES       = collection.omdoc
BUTFILES 	= catalogue.omdoc pvs.omdoc# collection.omdoc
include $(PREFIX)/lib/Makefile.vars

all:		html mml #ps
2:		42 i2 mml2
collection:	collection.html collection.xml collection.ps
include $(PREFIX)/lib/Makefile.in
