<!-- An XSL style sheet for creating BibTeX from OMDoc
     Copyright (c) 2000 Michael Kohlhase, 
     This style sheet is released under the Gnu Public License
     Initial version 20000902 by Michael Kohlhase, 
     send bug-reports, patches, suggestions to developers@omdoc.org
-->

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:omdoc="http://www.mathweb.org/omdoc"
		version="1.0">

<xsl:strip-space elements = "*" /> 
<xsl:output method="text"/>

<!-- the default behaviour empty -->
<xsl:template match="*"/>

<!-- we print a disclaimer and only look at top-level metadata -->
<xsl:template match="/">
  <xsl:text>% This file is automatically generated from an OpenMath Document </xsl:text>
  <xsl:text>&#xA;% by omdoc2bib.xsl do not edit&#xA;&#xA;</xsl:text>
  <xsl:apply-templates select="omdoc:omdoc/omdoc:metadata"/>
</xsl:template>

<!-- here we actually construct the bibtex entry, could be greatly enhanced  -->
<xsl:template match="omdoc:metadata">
  <xsl:variable name="type"><xsl:value-of select="dc:title"/></xsl:variable>
  <xsl:text>@</xsl:text>
  <xsl:choose>
    <xsl:when test="$type='article'"><xsl:text>article</xsl:text></xsl:when>
    <xsl:when test="$type='book'"><xsl:text>book</xsl:text></xsl:when>
    <xsl:when test="$type='report'"><xsl:text>report</xsl:text></xsl:when>
    <xsl:otherwise><xsl:text>misc</xsl:text></xsl:otherwise>
  </xsl:choose>
  <xsl:text>{</xsl:text>
  <xsl:value-of select="dc:creator"/>
  <xsl:text>:</xsl:text>
  <xsl:value-of select="dc:date"/>
  <xsl:text>,&#xA;  author = "</xsl:text>
  <xsl:for-each select="dc:creator">
    <xsl:apply-templates/>
    <xsl:if test="position()!=last()">
      <xsl:text> and </xsl:text>
    </xsl:if>
  </xsl:for-each>
  <xsl:if test="dc:title">
    <xsl:text>",&#xA;  title = "</xsl:text>
    <xsl:value-of select="dc:title"/>
  </xsl:if>
  <xsl:if test="dc:date">
    <xsl:text>",&#xA;  year = "</xsl:text>
    <xsl:value-of select="dc:date"/>
  </xsl:if>
  <xsl:if test="dc:publisher">
    <xsl:text>",&#xA;  publisher = "</xsl:text>
    <xsl:value-of select="dc:publisher"/>
  </xsl:if>
  <xsl:if test="dc:description">
    <xsl:text>",&#xA;  description = "</xsl:text>
    <xsl:value-of select="dc:Description"/>
  </xsl:if>
  <xsl:text>"}</xsl:text>
  </xsl:template>
</xsl:stylesheet>

<!-- todo: 
  - be more clever about the date, e.g. take the first four digits only
  - be more clever about the entry type and key (contains blanks now)
  - introduce the other features somewhere
  - look at xsl:base (see the recent declaration)
  -->
