PREFIX          = ../..
include $(PREFIX)/doc/Makefile.vars

# 	The name of your master tex file without ending .tex
TARGET		= cmml2om

all:	$(PDF) $(PS) 
include $(PREFIX)/doc/Makefile.in
include $(PREFIX)/lib/Makefile.clean.in

